### ISSUE TITLE
Is there any possibility to pass password for VNC Server?

### ISSUE THREAD

**Issue by monokbaev** [roerohan/react-vnc#15]
How to add password, if VNC server requires it?

**Comment by roerohan** [comment]
@monokbaev , sorry for the late response.

https://github.com/roerohan/react-vnc/blob/01afe07b5801087fbf11fec366896c980986ac54/src/lib/VncScreen.tsx#L95-L98

I haven't tried it with a password yet, but this part should ensure that you get a prompt on your browser in case the VNC server requires a password.
