### ISSUE TITLE
How to disconnect a session ?

### ISSUE THREAD

**Issue by dorroddorrod** [roerohan/react-vnc#18]
Hi,
How can i disconnect a session from a noVNC client ? 
I noticed when i'm not disconnecting and move to other page in my application and then trying to reconnect again its getting stuck cause the session is still there.

**Comment by roerohan** [comment]
Thanks for raising this issue @dorroddorrod !

I've recently added v0.2.9
You can use a ref (such as the following) to access the `connect()` and `disconnect()` methods.
https://github.com/roerohan/react-vnc/blob/main/src/App.tsx#L8

Here's a sample of how to use the ref.
https://github.com/roerohan/react-vnc/blob/main/src/App.tsx#L40-L53

**Comment by roerohan** [comment]
In #28 , I've also added support for the following methods from `RFB`

```
sendCredentials,
sendKey,
sendCtrlAltDel,
focus,
blur,
machineShutDown,
machineReboot,
machineReset,
clipboardPaste
```
