### ISSUE TITLE
Pass multiple protocols in rfbOptions.wsProtocols

### ISSUE THREAD

**Issue by devpilot** [roerohan/react-vnc#45]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

If I have multiple protocols to pass its not working out with `wsProtocols: string`. On noVnc they are accepting array for `wsProtocols. this._wsProtocols = options.wsProtocols || [];`
https://github.com/novnc/noVNC/blob/295004cabe262367a4df32257d8eb8517bfc4ae1/core/rfb.js#L119

### Proposed solution (optional)

Therefore I'm proposing to add `wsOptions: string | string[]` type in RFBOptions

**Comment by roerohan** [comment]
Hi @devpilot 
Thanks for reporting this issue! I see that you've made the aforementioned change on your fork, and I believe the change you made fixes the issue.

I made a PR for the change from your fork (#47), and I'll merge it into the `main` branch of this repository. Although I'll test it out on my own too, it would be great if you could confirm that the change works and doesn't break anything.

Thanks again for your contribution to the repository!
